"""empty message

Revision ID: 2d8f3f13060b
Revises: 
Create Date: 2023-06-10 12:45:53.858019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8f3f13060b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('nickname', sa.String(length=255), nullable=False, comment='昵称'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('description', sa.String(length=1024), nullable=True, comment='简介'),
    sa.Column('isadmin', sa.Boolean(), nullable=False, comment='是否是管理员'),
    sa.Column('key', sa.String(length=20), nullable=False, comment='Key'),
    sa.Column('img', sa.String(length=1024), nullable=True, comment='头像'),
    sa.Column('createdate', sa.Date(), nullable=False, comment='创建时间'),
    sa.Column('lastlogin', sa.Date(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
